FROM ubuntu:20.04

RUN set +x \
    && apt-get update \
    && apt-get install -y \
        curl \
        iptables \
        iproute2 \
        iputils-ping \
        net-tools \
        dnsutils \
        curl \
    && :
